#pragma once
#include <iostream>

std::string en_US = R"({
    "disconnect.isBanned": "You are banned!\n\nReason: %1$s \nEnd Time: %2$s",
    "disconnect.ipIsBanned": "Your IP is banned:\n\nReason: %1$s \nEnd Time: %2$s",
    "disconnect.defaultReason": "You are banned by Admin",
    "disconnect.forever": "Forever",
    "disconnect.clientNotAuth": "The client is not logged in! \n\nTo access the server, log in to your Xbox account!",
    "command.ban.desc": "Ban a player",
    "command.ban.success": "Player %1$s is successfully banned, unban date: %2$s",
    "command.ban.isBanned": "Player %1$s is already banned",
    "command.unban.desc": "unban a player",
    "command.unban.success": "Player %1$s is successfully unbanned!",
    "command.unban.notBanned": "Player %1$s is not banned!",
    "command.banip.desc": "ban an IP",
    "command.banip.success": "IP %1$s is successfully banned, unban date: %2$s",
    "command.banip.isBanned": "IP %1$s is already banned",
    "command.unbanip.desc": "unban an IP",
    "command.unbanip.success": "IP %1$s is successfully unbanned!",
    "command.unbanip.notBanned": "IP %1$s is not banned!",
    "command.error.invalidTime": "The ban duration must be 1 minute or greater!",
    "command.error.invalidCommandOrigin": "This command can only be executed by the player or the console!",
    "permission.error.invalidLevel": "Invalid command permission level! Reset to default!",
    "permission.warning.dangerousLevel": "[WARNING] Setting the command permission level to 0 is dangerous! This means that everyone can use this plugin command!",
    "command.banlist.desc": "Query ban list",
    "command.banlist.players.showInfo": "Player %1$s is banned by %2$s, reason: %3$s , End Time: %4$s",
    "command.banlist.ips.showInfo": "IP %1$s is banned by %2$s, reason: %3$s ,End Time: %4$s",
    "command.banlist.noBans": "No banned information was queried",
    "command.source.console": "Console",
    "error.fileIsBroken": "File %1$s is broken, trying to generate a new one."
})";


std::string zh_CN = R"({
    "disconnect.isBanned": "你已被服务器封禁！\n\n原因： %1$s \n解封时间： %2$s",
    "disconnect.ipIsBanned": "你的IP地址已被服务器封禁！\n\n原因： %1$s \n解封时间： %2$s",
    "disconnect.defaultReason": "你已被管理员封禁",
    "disconnect.forever": "永久封禁",
    "disconnect.clientNotAuth": "客户端未登录！\n\n如需进入服务器，请登录Xbox账户！",
    "command.ban.desc": "封禁一名玩家",
    "command.ban.success": "已成功封禁玩家 %1$s ， 解封日期： %2$s",
    "command.ban.isBanned": "玩家 %1$s 已经被封禁",
    "command.unban.desc": "解封一名玩家",
    "command.unban.success": "已成功解除玩家 %1$s 的封禁",
    "command.unban.notBanned": "无法解除封禁，玩家 %1$s 未被服务器封禁！",
    "command.banip.desc": "封禁一个IP地址",
    "command.banip.success": "已成功IP地址 %1$s ，解封日期： %2$s",
    "command.banip.isBanned": "IP地址 %1$s 已经被封禁",
    "command.unbanip.desc": "解封一个IP地址",
    "command.unbanip.success": "已成功IP地址 %1$s 的封禁",
    "command.unbanip.notBanned": "无法解除封禁，IP地址 %1$s 未被服务器封禁！",
    "command.error.invalidTime": "封禁时长必须大于等于1分钟！",
    "command.error.invalidCommandOrigin": "该命令只能由玩家或控制台执行！",
    "permission.error.invalidLevel": "无效的命令权限等级！已重置为默认值！",
    "permission.warning.dangerousLevel": "[警告] 将命令权限等级设置为 0 是十分危险的！这意味着所有人都可以使用本插件命令！",
    "command.banlist.desc": "查询封禁列表",
    "command.banlist.players.showInfo": "玩家 %1$s 已被 %2$s 封禁，封禁原因：%3$s ，截止日期：%4$s",
    "command.banlist.ips.showInfo": "IP地址 %1$s 已被 %2$s 封禁，封禁原因：%3$s ，截止日期：%4$s",
    "command.banlist.noBans": "没有查询到封禁信息",
    "command.source.console": "控制台",
    "error.fileIsBroken": "文件 %1$s 已损坏！正在重新生成文件！"
})";
